name: ci

on:
  pull_request: {}
  push:
    branches:
      - develop

jobs:
  bandit:
    name: bandit
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: bandit
        uses: ./.github/actions/bandit
        with:
          args: -r .

  black:
    name: black
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: black
        uses: ./.github/actions/black
        with:
          args: --check --diff .

  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: flake8
        uses: ./.github/actions/flake8
        with:
          args: .

  pylint:
    name: pylint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: pylint
        uses: ./.github/actions/pylint
        with:
          args: .

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: pytest
        uses: ./.github/actions/pytest
        with:
          entrypoint: ./.github/actions/pytest/entrypoint.sh

  safety:
    name: safety
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: safety
        uses: ./.github/actions/safety
        with:
          args: -r requirements.txt
